### ISSUE TITLE
organization

### ISSUE THREAD

**Issue by anchxng** [McrIntllgnc/discord-side-bar#1]
hi vyas. just saw this repo and wanted to give some tips.  you should organize all of your code into folders and have your readme/gitignore/license by themselves. also thanks for follwing me

**Comment by vdhr** [comment]
this is my first repo so thanks for the feedback @ksu-tech :))
hopefully as i start to use github more i think i'll slowly become better at it

**Comment by anchxng** [comment]
are you learning js right now

**Comment by anchxng** [comment]
and you should keep a readme and license

**Comment by vdhr** [comment]
ye im learning js
ok thanks
